version: "3"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk11
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "/usr/local/bin/docker:/usr/local/bin/docker" # "$(which docker):$(which docker)"
    environment:
      - DOCKER_HOST=tcp://socat:2375
    links:
      - socat
  socat:
    container_name: socat
    image: alpine/socat:latest
    restart: always
    ports:
      - 127.0.0.1:2376:2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
volumes:
  jenkins_data:
    driver: local
